name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  FILE_NAME: radish-system-map

jobs:
  build-gh-pages:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Typst
        uses: typst-community/setup-typst@v3

      - name: Download radishom
        run: |
          git clone https://github.com/QuadnucYard/radishom.git $HOME/.local/share/typst/packages/local/radishom/0.1.0

      - name: Download font assets
        run: |
          mkdir -p assets/fonts/
          curl -L https://github.com/QuadnucYard/radish-metro/releases/download/assets/fonts.tar.gz | tar -xvz -C web/src/assets/fonts

      - name: Compile documents
        run: |
          typst fonts --ignore-system-fonts --variants --font-path web/src/assets/fonts/
          typst compile src/system-map/main.typ web/src/assets/generated/${{ env.FILE_NAME }}.svg --root . --ignore-system-fonts --font-path web/src/assets/fonts

      - uses: oven-sh/setup-bun@v2
      - name: Build web
        run: |
          cd web
          bun install
          bun build-only

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./web/dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
